# backend/cloudbuild.yaml
substitutions:
  _SERVICE: sec-scraper
  _REGION:  us-central1
  _REPO:    sec-scraper-repo

steps:
# 1 Build image from ./backend
- name: gcr.io/cloud-builders/docker
  dir: backend
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
    - .

# 2 Push to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

# 3 Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated

images:  # optional metadata
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
